function [data,textdata] = importfile1(fileToRead1,varPrefix)
%IMPORTFILE1(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read
%  varPrefix: Currently unused.

%  Auto-generated by MATLAB on 23-Nov-2011 10:51:13

% Import the file

sheetName='VersionForImport';
[numbers, strings, raw] = xlsread([getResultsDir() fileToRead1], sheetName);
if ~isempty(numbers)
    data =  numbers;
else
    data = [];
end
if ~isempty(strings)
    textdata =  strings;
end

if ~isempty(strings) && ~isempty(numbers)
    [strRows, strCols] = size(strings);
    [numRows, numCols] = size(numbers);
    likelyRow = size(raw,1) - numRows;
    % Break the data up into a new structure with one field per column.
    if strCols == numCols && likelyRow > 0 && strRows >= likelyRow
        newData1.colheaders = strings(likelyRow, :);
    end
end
